theme: minima
title: "The Blog"
author: Jerome Paliakkara
email: jerome.george.001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jerome Paliakkara's blog. Software engineering, travel, cooking, cocktails, magic, photography; can't think of more right now.

# social links
twitter_username: JeromeGeorgeP # DO NOT include the @ character, or else the build will fail!
github_username:  jerome9189 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
